export const FETCH_HIGHLIGHTS_REQUEST = "FETCH_HIGHLIGHTS_REQUEST";
export const FETCH_HIGHLIGHTS_SUCCESS = "FETCH_HIGHLIGHTS_SUCCESS";
export const FETCH_HIGHLIGHTS_FAILURE = "FETCH_HIGHLIGHTS_FAILURE";
